apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-application-properties-config-map
data:
  application.properties: |
    [
     server.port: 8443
     inventory.service: https://inventory-service/inventory
     logging.level.org.springframework=DEBUG
     logging.level.root=DEBUG
    ]