security:
  user:
    password: password
  ignored:
  - "*.bundle.*"
logging:
  level:
    org.springframework.security: DEBUG
zuul:
  routes:
    resource:
      path: /orders/**
      url: http://localhost:9000/orders
