apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: ecomm-authn-policy
spec:
  targets:
  - name: orders-service
  - name: inventory-service
  peers:
  - mtls:
      mode: STRICT
  origins:
  - jwt:
      issuer: "sts.ecomm.com"
      jwksUri: "http://sts-service/oauth/token_key"
  principalBinding: USE_ORIGIN
