apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: ecomm-authn-policy
spec:
  targets:
  - name: orders-service
  - name: inventory-service
  peers:
  - mtls:
      mode: STRICT
  origins:
  - jwt:
      issuer: "sts.ecomm.com"
      #jwksUri: "https://raw.githubusercontent.com/microservices-security-in-action/samples/master/chapter10/sample01/keystores/jwtkey.jwk"
      jwksUri: "https://raw.githubusercontent.com/istio/istio/release-1.0/security/tools/jwt/samples/jwks.json"
  principalBinding: USE_ORIGIN



